FROM python:3.12-slim

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY dashboard/streamlit_app.py dashboard/streamlit_app.py

ENV ENV=prod

CMD streamlit run dashboard/streamlit_app.py \
    --server.port=$PORT \
    --server.address=0.0.0.0 \
    --server.headless=true
